services:
  postgres:
    container_name: postgres_container
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: PgWithNest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.config
    ports:
      - 6379:6379
    networks:
      - redis-network

volumes:
  postgres_data:
  redis:
  redis-config:

networks:
  redis-network:
    driver: bridge