services:
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  postgres:
    container_name: postgres_container
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.config
    ports:
      - 6379:6379
    networks:
      - redis-network

  nats:
    image: nats:alpine3.17
    container_name: nats-main
    env_file:
      - .env
    environment:
      NATS_SERVERS: ${NATS_SERVERS}
      NATS_USERNAME: ${NATS_USERNAME}
      NATS_PASSWORD: ${NATS_PASSWORD}
    command: "--js -m 8009"
    volumes:
      - ./data:/data
    ports:
      - "4222:${NATS_PORT}"
      - "8009:8009"

volumes:
  postgres_data:
  redis:
  redis-config:
  minio_storage:

networks:
  redis-network:
    driver: bridge