services:
  postgres:
    container_name: postgres_container
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: PgWithNest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: